openapi: 3.0.2
info:
  title: societe-person-api
  version: 1.0.0
  description: A brand new API with no content.  Go nuts!
paths:
  /persons:
    get:
      tags:
        - Person
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonDto'
          description: Get all persons in the base
      operationId: findAllPersons
      summary: Get all persons
    post:
      requestBody:
        description: 'Add person in the base '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDto'
        required: true
      tags:
        - Person
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
          description: Created person successfully
      operationId: createPerson
      summary: Create person
  /adresses:
    summary: Path used to manage the list of adressedtos.
    description: >-
      The REST endpoint/path used to list and create zero or more `adresseDto` entities.  This path
      contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
    get:
      tags:
        - Adresse
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdresseDto'
          description: Successful response - returns an array of `adresseDto` entities.
      operationId: findAdresses
      summary: List All adresses
      description: Gets a list of all `adresseDto` entities.
    post:
      requestBody:
        description: A new `adresseDto` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdresseDto'
        required: true
      tags:
        - Adresse
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdresseDto'
          description: Successful response.
      operationId: createAdresse
      summary: Create a adresse
      description: Creates a new instance of a `adresseDto`.
  '/adresses/{id}':
    summary: Path used to manage a single adresseDto.
    description: >-
      The REST endpoint/path used to get, update, and delete single instances of an `adresseDto`.  This
      path contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete
      tasks, respectively.
    get:
      tags:
        - Adresse
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdresseDto'
          description: Successful response - returns a single `adresseDto`.
        '404':
          content:
            application/json:
              schema:
                type: string
          description: Successful response - returns a single `adresseDto`.
      operationId: findAdresseById
      summary: Get an adress with id
      description: Gets the details of a single instance of a `adresseDto`.
    put:
      requestBody:
        description: Updated `adresseDto` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdresseDto'
        required: true
      tags:
        - Adresse
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdresseDto'
          description: Successful response.
      operationId: updateAdresse
      summary: Update an adress
      description: Updates an existing `adresseDto`.
    delete:
      tags:
        - Adresse
      responses:
        '204':
          content:
            application/json:
              schema:
                type: boolean
          description: Successful response.
      operationId: deleteAdresse
      summary: Delete an adress
      description: Deletes an existing `adresseDto`.
    parameters:
      -
        name: id
        description: A unique identifier for a `adresseDto`.
        schema:
          format: int64
          type: integer
        in: path
        required: true
  '/persons/{id}':
    summary: Path used to manage a single personDto.
    description: >-
      The REST endpoint/path used to get, update, and delete single instances of an `personDto`.  This
      path contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete
      tasks, respectively.
    get:
      tags:
        - Person
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
          description: Successful response - returns a single `personDto`.
        '404':
          content:
            application/json:
              schema:
                type: string
          description: Successful response - returns a single `personDto`.
      operationId: findPersonById
      summary: Get a person by id
      description: Gets the details of a single instance of a `personDto`.
    put:
      requestBody:
        description: Updated `personDto` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDto'
        required: true
      tags:
        - Person
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
          description: Successful response.
      operationId: updatePerson
      summary: Update a person
      description: Updates an existing `personDto`.
    delete:
      tags:
        - Person
      responses:
        '204':
          content:
            application/json:
              schema:
                type: boolean
          description: Successful response.
      operationId: deletePerson
      summary: Delete a person by id
      description: Deletes an existing `personDto`.
    parameters:
      -
        name: id
        description: A unique identifier for a `personDto`.
        schema:
          format: int64
          type: integer
        in: path
        required: true
  /entreprises:
    summary: Path used to manage the list of enterprisedtos.
    description: >-
      The REST endpoint/path used to list and create zero or more `enterpriseDto` entities.  This path
      contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
    get:
      tags:
        - Entreprise
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntrepriseDto'
          description: Successful response - returns an array of `enterpriseDto` entities.
      operationId: findEnterprises
      summary: List All enterprises
      description: Gets a list of all `enterpriseDto` entities.
    post:
      requestBody:
        description: A new `enterpriseDto` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntrepriseDto'
        required: true
      tags:
        - Entreprise
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntrepriseDto'
          description: Successful response.
      operationId: createEnterprise
      summary: Create a enterprise
      description: Creates a new instance of a `enterpriseDto`.
  '/entreprises/{id}':
    summary: Path used to manage a single enterpriseDto.
    description: >-
      The REST endpoint/path used to get, update, and delete single instances of an `enterpriseDto`.
      This path contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and
      delete tasks, respectively.
    get:
      tags:
        - Entreprise
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntrepriseDto'
          description: Successful response - returns a single `enterpriseDto`.
        '404':
          content:
            application/json:
              schema:
                type: string
          description: Successful response - returns a single `enterpriseDto`.
      operationId: findEnterpriseById
      summary: Get an enterprise
      description: Gets the details of a single instance of a `enterpriseDto`.
    put:
      requestBody:
        description: Updated `enterpriseDto` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntrepriseDto'
        required: true
      tags:
        - Entreprise
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntrepriseDto'
          description: Successful response.
      operationId: updateEnterprise
      summary: Update a enterpriseDto
      description: Updates an existing `enterpriseDto`.
    delete:
      tags:
        - Entreprise
      responses:
        '204':
          content:
            application/json:
              schema:
                type: boolean
          description: Successful response.
      operationId: deleteEnterprise
      summary: Delete an enterprise
      description: Deletes an existing `enterpriseDto`.
    parameters:
      -
        name: id
        description: A unique identifier for a `enterpriseDto`.
        schema:
          format: int64
          type: integer
        in: path
        required: true
components:
  schemas:
    EntrepriseDto:
      description: Entreprise Dto
      required:
        - name
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        num_fiscale:
          type: string
        adresse_id:
          format: int64
          type: integer
        personnels:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/PersonDto'
    AdresseDto:
      description: Adresse Dto
      required:
        - adresse
      type: object
      properties:
        id:
          format: int64
          type: integer
        adresse:
          type: string
        ville:
          type: string
        pays:
          type: string
        code_postal:
          type: string
    PersonDto:
      description: Person Dto
      required:
        - name
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        lastName:
          type: string
        post:
          enum:
            - PRESIDENT
            - DRH
            - ADMIN
            - EMPLOYEE
          type: string
        enterprise_id:
          format: int64
          type: integer
        adresse_id:
          format: int64
          type: integer
